version: '3.8'

services:
  main:
    image: sparkles-bitaxe-monitor:latest
    build:
      context: .
      dockerfile: docker-compose.yml
    container_name: sparkles-bitaxe-monitor
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATA_DIR=/umbrel/app-data/data
      - REACT_APP_API_URL=http://localhost:3000/api
    ports:
      - "3000:3000"
    volumes:
      - ./data:/umbrel/app-data/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
