version: '3.8'

services:
  app:
    image: brentparks/bitaxe-monitor-frontend:1.0.0
    restart: unless-stopped
    networks:
      - sparkles-bitaxe-monitor-network
    depends_on:
      - backend

  backend:
    image: brentparks/bitaxe-monitor-backend:1.0.0
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATA_DIR=${APP_DATA_DIR}/data
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    networks:
      - sparkles-bitaxe-monitor-network

  app_proxy:
    image: getumbrel/app-proxy:latest
    restart: unless-stopped
    environment:
      - APP_PORT=80
      - APP_HOST=sparkles-bitaxe-monitor_app_1
    ports:
      - "3000:80"
    networks:
      - sparkles-bitaxe-monitor-network
    depends_on:
      - app

networks:
  sparkles-bitaxe-monitor-network:
    driver: bridge
