version: '3.8'

services:
  sparkles-bitaxe-monitor:
    image: sparkles-bitaxe-monitor:latest
    container_name: sparkles-bitaxe-monitor
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATA_DIR=/umbrel/app-data/data
      - REACT_APP_API_URL=http://localhost:3000/api
    ports:
      - "3000:3000"
    volumes:
      - ./data:/umbrel/app-data/data
